# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:

        card_thumb:
            quality: 75
            filters:
                thumbnail: {size: [800, 330], mode: outbound}

        post:
            quality: 75
            filters:
                scale: {dim: [1200, 1200], mode: outbound}

        carousel:
            quality: 95
            filters:
                scale: { dim: [ 1600, 1600 ], mode: outbound }

        user_profile:
            quality: 75
            filters:
                thumbnail: {size: [60, 60], mode: outbound}
